version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"  # Match the min version from pyproject.toml
  jobs:
    pre_build:
      - pip install pydoc-markdown
      - pydoc-markdown

mkdocs:
  configuration: mkdocs.yaml
  fail_on_warning: false

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs