version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"  # Match the min version from pyproject.toml
  jobs:
    pre_build:
      - pydoc-markdown --build --site-dir _readthedocs

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - _readthedocs