version: 2

build:
  os: "mac-os v 15.5"
  tools:
    python: ">3.8"
  # We recommend using a requirements file for reproducible builds.
  # This is just a quick example to get started.
  # https://docs.readthedocs.io/page/guides/reproducible-builds.html
  jobs:
    pre_install:
      - poetry add mkdocs-material

mkdocs:
  configuration: mkdocs.yml