version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"  # Match the min version from pyproject.toml

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
  system_packages: false