site_name: Moduli Generator
site_description: A tool for generating SSH moduli files
site_url: !ENV READTHEDOCS_CANONICAL_URL
repo_url: https://github.com/beckerwilliams/moduli_generator
repo_name: beckerwilliams/moduli_generator

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
    #
    #    text: Roboto        # Font for body text
    #    code: Roboto Mono   # Font for code blocks
    #
    #      text: Inter
    #      code: JetBrains Mono
    #
    # Classic and readable
#      text: Open Sans
#      code: Source Code Pro
#
#    # Elegant and professional
#      text: Lato
#      code: Fira Code
#
#    # System fonts (no web fonts loaded)
#      text: -apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, i
#      code: SFMono-Regular, Consolas, Liberation Mono, Menlo, monospace




extra_javascript:
  - javascript/readthedocs.js

nav:
  - Home: index.md
  - QuickStart: readme.md
  - usage: usage.md
  - api: api.md
  - About: about.md
#  - API:
#      - ModuliGenerator: moduli_generator.md
#      - Config: config.md
#      - ArgParser: argparser.md
#      - DBConnector: db.md
#      - ChangeLog Generator: changelog_generator.md
#  - About: about.md
#  - Usage: usage.md
#  - Documentation:
#      - Analysis: moduli_generator_analysis_and_improvements.md
#      - Improvements: project_improvement_recommendations.md
#      - Refactoring: REFACTORING_SUMMARY.md
#      - ChangeLog Configuration Guide: CHANGELOG_CONFIGURATION.md
#      - PyCharmConfigurationStatus: PYCHARM_CONFIGURATION_STATUS.md
#      - PyCharmDocstringFormatRecommendation: PYCHARM_DOCSTRING_FORMAT_RECOMMENDATION.md
#      - MkDocs Setup: PYCHARM_MKDOCS_SETUP.md
#  - License:
#      - license.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            members_order: source
            separate_signature: true
            members: true
            filters:
              - "!^_"  # Exclude private members (those starting with _)