site_name: Moduli Generator
site_description: A tool for generating SSH moduli files
site_url: !ENV READTHEDOCS_CANONICAL_URL
repo_url: https://github.com/beckerwilliams/moduli_generator
repo_name: beckerwilliams/moduli_generator

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_javascript:
  - javascript/readthedocs.js

nav:
  - Home: index.md
  - API: API.md
  - About: about.md
  - Copyright: copyright.md
  - Config: config.md
  - Documentation:
      - Analysis: moduli_generator_analysis_and_improvements.md
      - Improvements: project_improvement_recommendations.md
      - Refactoring: REFACTORING_SUMMARY.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            members_order: source
            separate_signature: true
            members: true
            filters:
              - "!^_"  # Exclude private members (those starting with _)