site_name: Moduli Generator
site_description: A tool for generating SSH moduli files
site_url: https://moduli-generator.readthedocs.io/
repo_url: https://github.com/beckerwilliams/moduli_generator
repo_name: beckerwilliams/moduli_generator
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono

extra_javascript:
  - javascript/readthedocs.js

nav:
  - Home: index.md
  - API Reference:
      - API: API/index.md

  - Installation:
      - Overview: installation/index.md
      - Command Line Installer: installation/command_line_installer.md

  - User Guides:
      - Overview: user_guides/index.md
      - Usage: user_guides/usage.md
      - Restart: user_guides/restart.md

  - Database:
      - Overview: database/index.md
      - Integration: database/integration.md
      - MariaDB: database/mariadb.md
      - Schema Verification: database/schema_verification.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            members_order: source
            separate_signature: true
            members: true
            filters:
              - "!^_"
  - autorefs