[tool.poetry]
name = "moduli_generator"
version = "2.1.12"
description = "Command Line Utility to build moduli for /usr/local/etc/ssh/moduli_file"
authors = ["Ron Williams <becker.williams@gmail.com>"]
license = "MIT"
readme = "README.rst"
keywords = ["cryptography", "ssh", "moduli", "security"]
classifiers = [
	"Development Status :: 5 - Production/Stable",
	"Intended Audience :: System Administrators",
	"Topic :: Security :: Cryptography",
	"Programming Language :: Python :: 3.12",
]
packages = [
	{ include = "config" },
	{ include = "db" },
	{ include = "moduli_generator" }
]
include = [
	"docs/**/*"
]
exclude = [
	"*.cnf"  # No Mariadb Configuration Files (Usually Contain Passwords)
]

[tool.poetry.dependencies]
python = "^3.12"
mariadb = "^1.1.12"
configparser = "^7.2.0"
toml = "^0.10.2"
poetry-core = "^2.1.3"

[tool.poetry.group.dev.dependencies]
sphinx = "^7.2.6"
sphinxcontrib-jquery = "^4.1"
sphinx-rtd-theme = "^3.0.2"

[tool.poetry.scripts]
moduli_generator = "moduli_generator.cli:main"
build_docs = "moduli_generator.scripts.build_docs:main"
moduli_stats = "db.scripts.moduli_stats:main"
write_moduli = "moduli_generator.scripts.write_moduli:main"
generate_changelog = "moduli_generator.scripts.changelog_generator:main"
install_schema = "db.scripts.install_schema:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
Homepage = "https://github.com/beckerwilliams/moduli_generator"
Documentation = "https://github.com/beckerwilliams/moduli_generator/blob/main/README.rst"
Repository = "https://github.com/beckerwilliams/moduli_generator.git"
Issues = "https://github.com/beckerwilliams/moduli_generator/issues"