[project]
name = "moduli_generator"
description = "A secure, high-performance SSH moduli generator with database integration for cryptographic key exchange operations"
authors = [
	{ name = "Ron Williams", email = "becker.williams@gmail.com" }
]
license = { text = "MIT" }
keywords = ["cryptography", "ssh", "moduli", "security"]
version = "2.1.28"
readme = "README.rst"
classifiers = [
	"Development Status :: 4 - Beta",
	"Intended Audience :: System Administrators",
	"Intended Audience :: Developers",
	"Intended Audience :: Information Technology",
	"Topic :: Security :: Cryptography",
	"Topic :: System :: Systems Administration",
	"Topic :: Security",
	"Topic :: Internet",
	"Topic :: Software Development :: Libraries :: Python Modules",
	"Environment :: Console",
	"Programming Language :: Python :: 3",
	"Programming Language :: Python :: 3.11",
	"Programming Language :: Python :: 3.12",
	"Programming Language :: Python :: 3.13",
	"Programming Language :: Python :: 3 :: Only",
	"Operating System :: POSIX :: Linux",
	"Operating System :: Unix",
	"Operating System :: MacOS",
	"Environment :: Console",
	"Natural Language :: English",
	"Typing :: Typed"
]
requires-python = ">=3.11,<4.0"
dependencies = [
	"mariadb (==1.1.13)",
	"toml>=0.10.2",
	"configparser>=7.2.0",
	"black (>=25.0,<26.0.0)",
	"poetry-core (>=2.0.0,<3.0.0)",
	"typing-extensions (>=4.14.1,<5.0.0)",
	"sphinx-rtd-theme (>=3.0.2,<4.0.0)",
	"pytest (>=8.4.1,<9.0.0)"
]
include = [
	"data/**/*.sql",
	"data/**/*.conf",
	"data/**/*.sh",
	"data/**/*.json",
	"doc/**/*",
	"**/*.md",
	"**/*.rst"
]

[project.optional-dependencies]
dev = [
	"sphinx>=7.2.6",
	"sphinxcontrib-jquery>=4.1",
	"sphinx-rtd-theme>=3.0.2",
	"myst-parser>=2.0.0",
	"pytest>=8.4.1",
	"pytest-cov>=4.0.0",
	"pytest-mock>=3.12.0",
	"pytest-asyncio>=0.23.0",
]

[project.scripts]
moduli_generator = "moduli_generator.cli:main"
moduli_stats = "db.scripts.moduli_stats:main"
changelog = "changelog_generator.scripts.print:main"
install_schema = "db.scripts.install_schema:main"
build_docs = "moduli_generator.scripts.build_docs:main"
cli = "moduli_generator.cli:main"

[project.urls]
Homepage = "https://github.com/beckerwilliams/moduli_generator"
Documentation = "https://github.com/beckerwilliams/moduli_generator/blob/main/README.rst"
Repository = "https://github.com/beckerwilliams/moduli_generator.git"
Issues = "https://github.com/beckerwilliams/moduli_generator/issues"

[tool.poetry]
packages = [
	{ include = "moduli_generator" },
	{ include = "db" },
	{ include = "config" },
	{ include = "test" },
	{ include = "changelog_generator" }
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
[project.group.dev.dependencies]
sphinx = "^8.2.3"
