CREATE USER 'moduli_generator'@'10.1.1.44'
IDENTIFIED BY 'cBZuvHjIIN2S5Nr'
WITH MAX_QUERIES_PER_HOUR 500
MAX_CONNECTIONS_PER_HOUR 100
MAX_UPDATES_PER_HOUR 200
MAX_USER_CONNECTIONS 50;
GRANT ALL PRIVILEGES ON mod_gen.* TO 'moduli_generator'@'10.1.1.44' WITH GRANT OPTION;
FLUSH PRIVILEGES;